[project]
name = "AGI Concept API - artificial intelligence Google Gemini 2.0 Flash"
version = "0.1.0"
description = "AGI Concept API - artificial intelligence Google Gemini 2.0 Flash"
requires-python = ">=3.8"
dependencies = [
    "flask",
    "flask-compress",
    "requests"
]
